### ISSUE TITLE
Facing this issue in BGMI and it may also be there for other games too 

### ISSUE THREAD

**Issue by EndLess728** [DerpFest-AOSP/packages_apps_GamingMode#1]
Use Case -

1. Fresh installed BGMI and added it to gaming mode
2. Opened BGMI and then it asked for storage permission, and I gave it permission.
3. I was playing the game and I had opened gaming mode popup then I thought to open my mic and I tried to turn it on. It asked for permission but at that time I was stuck there. I was not able to click on allow or deny in the permission popup.

I think there is windows conflict when gaming mode popup was there and suddenly permission popup pops it doesn't allow user to click on permission popup.

**Comment by NurKeinNeid** [comment]
adressed this here:

https://github.com/DerpFest-11/frameworks_base/commit/5eefb31ae9317b8cd9538986f893058bbb90e028

**Comment by EndLess728** [comment]
Thanks man
